# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mark/Development/cg/CG/src/executables/01_Start/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mark/Development/cg/cmake/DefaultExecutable.cmake))

/Users/mark/Development/cg/CG/BUILD_Xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.9.0/bin/cmake -H/Users/mark/Development/cg/CG/src -B/Users/mark/Development/cg/CG/BUILD_Xcode
